# Build settings
markdown: kramdown
comments:
  provider: disqus
  disqus :
    short_name : enricoteotti

permalink: "/:title/"

gems:
  - jekyll-redirect-from

# Build settings
source: source
destination: public

# Site settings
title: "Hi, I am Enrico"
description: > # this means to ignore newlines until "email:"
   I craft maintainable software that delivers business value. Born and educated in Italy, became Australian now working in New York City.

email: enrico@teotti.com
#blog logo
main_logo: "/assets/images/me_tama.jpg"
logo: "/assets/images/ita_aus_flag.jpg"
# blog cover
cover: "/assets/images/hero_image.jpg"

name: 'Enrico Teotti'
author: 'Enrico Teotti'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://teotti.com/" # the base hostname & protocol for your site
#url: "http://localhost:4000/" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/agenteo
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	linkedin
    url:	https://www.linkedin.com/in/agenteo/
    desc: Connect with me Linkedin
    share_url:
    share_title:
    share_link:

  - icon:	github
    url:	https://github.com/agenteo
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
